use_frameworks!

target 'BCAlertView_Example' do
  pod 'BCAlertView', :path => '../'

  target 'BCAlertView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
