use_frameworks!
#pod 'BCAlertView', :path => '../' # 指定路径
target 'BCAlertView_Example' do
  pod 'BCAlertView', :podspec => '../BCAlertView.podspec'

  target 'BCAlertView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
